
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy app
        run: echo "deploying app to ${{github.event.inputs.environment}}"
