on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"    

  pull_request:
    branches:
      - main
      - "release/**"


jobs:
  test:
    runs-on: ubuntu-latest
    seteps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Run test
      run: npm test  